### ISSUE TITLE
Example for 1D

### ISSUE THREAD

**Issue by mmarras** [djsilva99/heatrapy#14]
Hi, 

would it be possible to give an example for the 1D case potentially where the external temperature changes after t_1 or something? 

Would also be nice to get an example for how the systemsObject1D works. Especially the boundary tuple makes no sense to me atm.

Thanks

**Comment by djsilva99** [comment]
Hi @mmarras 

Sorry for the very late reply. I did not pay attention to the issues until very recently.

- If a reply is still useful, can you explain in more detail the example you require?
- the boundary tuple for the `systemsObject1D` class is a bit different from the `SingleObject1D` case. Each tuple element from the outer tuple represents a single object. The first tuple entry of each single object represents the object, and the second represents the external temperature of the object. If the second element is 0 then the object is insulated and not in contact with external environment.
