### ISSUE TITLE
[ Bugs ] Few simple and handy bugs

### ISSUE THREAD

**Issue by MCilento93** [djsilva99/heatrapy#2]
Dear Mr. D.J. Silva,

I am using your package ‘heatrapy’ to do simple 1D Thermal model, and this thread to signal you few bugs. First and foremost, I would like to thank you for implementing it, because boost a fresh implementation of FD approach on python (I come from a different PL), and because it is very handy.

PS: below I would like to share some misprints I found working on your project.
1.	the name of the package maybe is wrong in the presentation page, top left figure [here](https://djsilva99.github.io/heatrapy/docs/single_thermal_object/)
2.	wrong instance variable attribute name, maybe contact rather than contacts (row 102 within def contactFilter(self,object)
3.	Borders is a tuple, in the [example](https://djsilva99.github.io/heatrapy/example/) is a list (and written two times?)
4.	The description of single_object is maybe wrong for Q and Q0, the first entry value is the value of the flux per unit volume 

Thank you for the comprehension,

Best regards,

**Comment by djsilva99** [comment]
Thanks for reporting these bugs. I will fix them as soon as possible.

Best regards

**Comment by djsilva99** [comment]
I fixed the four points.

Thanks
