### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by ArtemioA** [djsilva99/heatrapy#38]
Hi,
Can tell me how to change Temperature of the bodies? Not the ambient temperature?

**Comment by djsilva99** [comment]
Hello!

Let's say that you instantiate a single object in 2D:
 ```
object2D = SingleObject2D(...)
```
You can access the temperature matrix like this:
```
object2D.object.temperature`
```
Then you can assign any value in each matrix element. For example,
```
object2D.temperature[2][2] = 300
```

**Comment by ArtemioA** [comment]
Thank you so Much!
