### ISSUE TITLE
Spatial discretization

### ISSUE THREAD

**Issue by EgQuent** [djsilva99/heatrapy#9]
Dear Mister Silva,

I get the impression that inside the 2D sub-folder, the classes Object and SingleObject are asking for 'dx', 'dy' as space steps along the x- and y-axis, respectively. However when defining the material properties, temperatures, etc... on the calculation matrix, its the parameter 'size' that is used. Same to export the results. I cannot find in the code, where 'dx' and 'dy' have been taken into account.

In my case I want to to perform the calculation on an oven 800mm x 600mm, but I would like to perform the calculation on a 10mm square grid.
What do I don't understand?

Thanks,
Best regards

**Comment by djsilva99** [comment]
Sorry for the very, very late reply. 

The `dx` and `dy` are used by the solvers. For example:
https://github.com/djsilva99/heatrapy/blob/f5a2ff55d517b22edf087ad022a1ea50e6ba73d4/heatrapy/dimension_2/solvers/explicit_general.py#L59-L61

**Comment by djsilva99** [comment]
Since this is an old issue, I will close it for now.

**Comment by djsilva99** [comment]
Since this is an old issue, I will close it for now.
